"""add_guest_fields_to_appointments

Revision ID: 36568b13048f
Revises: f2ffff388b94
Create Date: 2026-04-29 17:59:37.428426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36568b13048f'
down_revision: Union[str, None] = 'f2ffff388b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('guest_name', sa.String(length=150), nullable=True))
    op.add_column('appointments', sa.Column('guest_phone', sa.String(length=20), nullable=True))
    op.add_column('appointments', sa.Column('guest_vehicle_number', sa.String(length=30), nullable=True))
    op.add_column('appointments', sa.Column('guest_vehicle_model', sa.String(length=100), nullable=True))
    op.alter_column('appointments', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'guest_vehicle_model')
    op.drop_column('appointments', 'guest_vehicle_number')
    op.drop_column('appointments', 'guest_phone')
    op.drop_column('appointments', 'guest_name')
    # ### end Alembic commands ###
