"""service_types_json

Revision ID: f2ffff388b94
Revises: 3a8ea54d72d8
Create Date: 2026-04-28 16:39:12.475191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2ffff388b94'
down_revision: Union[str, None] = '3a8ea54d72d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add nullable first, backfill existing rows, then set NOT NULL
    op.add_column('appointments', sa.Column('service_types', sa.JSON(), nullable=True))
    op.execute("UPDATE appointments SET service_types = to_json(ARRAY[service_type::text])")
    op.alter_column('appointments', 'service_types', nullable=False)
    op.drop_column('appointments', 'service_type')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('service_type', postgresql.ENUM('general_service', 'oil_change', 'tyre_change', 'brake_service', 'battery_replacement', 'full_service', 'repair', 'other', name='servicetype'), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'service_types')
    # ### end Alembic commands ###
